<?php
// Variables
return [
  "creatorName" => "Akhil S",
  "creatorUrl" => "https://ak-mart.com",
  "templateName" => "AK-Mart",
  "templateSuffix" => "AK-Mart Dashboard",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "AK-Mart — Advanced Mini-Mart & E-Commerce Management Platform. Smart Management for Modern Stores.",
  "templateKeyword" => "ak-mart, ecommerce, mini-mart, store management, inventory, pos, laravel admin panel",
  "licenseUrl" => "https://ak-mart.com/license/",
  "livePreview" => "https://ak-mart.com",
  "productPage" => "https://ak-mart.com",
  "support" => "https://ak-mart.com/support/",
  "adminTemplates" => "https://ak-mart.com",
  "bootstrapDashboard" => "https://ak-mart.com",
  "ogTitle" => "AK-Mart — Smart Management for Modern Stores",
  "ogImage" => "",
  "ogType" => "product",
  "documentation" => "https://ak-mart.com/docs",
  "changelog" => "https://ak-mart.com/changelog",
  "repository" => "https://github.com/akhilmeleppura/Ak-Mart",
  "gitRepo" => "Ak-Mart",
  "gitRepoAccess" => "https://ak-mart.com",
  "githubFreeUrl" => "https://github.com/akhilmeleppura/Ak-Mart",
  "facebookUrl" => "https://facebook.com/ak-mart",
  "twitterUrl" => "https://twitter.com/ak-mart",
  "githubUrl" => "https://github.com/akhilmeleppura",
  "dribbbleUrl" => "https://dribbble.com/ak-mart",
  "instagramUrl" => "https://instagram.com/ak-mart"
];