<?php
// Variables
return [
  "creatorName" => "AK",
  "creatorUrl" => "https://ak-ecom.com",
  "templateName" => "Ak Mart",
  "templateSuffix" => "Ak Mart Dashboard",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "AK Ecom - The Complete E-commerce Dashboard Solution.",
  "templateKeyword" => "ecommerce, dashboard, admin panel, ak ecom",
  "licenseUrl" => "https://ak-ecom.com/license/",
  "livePreview" => "https://ak-ecom.com",
  "productPage" => "https://ak-ecom.com",
  "support" => "https://ak-ecom.com/support/",
  "adminTemplates" => "https://ak-ecom.com",
  "bootstrapDashboard" => "https://ak-ecom.com",
  "ogTitle" => "AK Ecom - Complete E-commerce Dashboard",
  "ogImage" => "",
  "ogType" => "product",
  "documentation" => "https://ak-ecom.com/docs",
  "changelog" => "https://ak-ecom.com/changelog",
  "repository" => "https://github.com/ak-ecom",
  "gitRepo" => "ak-ecom-dashboard",
  "gitRepoAccess" => "https://ak-ecom.com",
  "githubFreeUrl" => "https://github.com/ak-ecom",
  "facebookUrl" => "https://facebook.com/ak-ecom",
  "twitterUrl" => "https://twitter.com/ak-ecom",
  "githubUrl" => "https://github.com/ak-ecom",
  "dribbbleUrl" => "https://dribbble.com/ak-ecom",
  "instagramUrl" => "https://instagram.com/ak-ecom"
];